@blog_community_api_HostAddress = http://localhost:5158/api

### Register User
POST {{blog_community_api_HostAddress}}/users/register
Content-Type: application/json

{
    "username": "testuser1",
    "email": "test1@example.com",
    "password": "P@ssword!"
}

### Login testuser1
POST {{blog_community_api_HostAddress}}/users/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser1",
  "password": "P@ssword!"
}

### Login testuser2
POST {{blog_community_api_HostAddress}}/users/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser2",
  "password": "P@ssword!"
}

### Existing user routes:
###
@userId1 = 019caffa-a63c-76c4-bd81-f4de94b3ce80
@username1 = testuser1
@email1 = test1@example.com
@token1 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTljYWZmYS1hNjNjLTc2YzQtYmQ4MS1mNGRlOTRiM2NlODAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWNhZmZhLWE2M2MtNzZjNC1iZDgxLWY0ZGU5NGIzY2U4MCIsImp0aSI6ImE2MzJmZmFkLTdhOGUtNDFiMy1iODgxLWI3ZjNlNTMwZTBhYSIsImlzcyI6ImJsb2ctY29tbXVuaXR5LWFwaSIsImF1ZCI6WyJibG9nLWNvbW11bml0eS1hcGktY2xpZW50IiwiYmxvZy1jb21tdW5pdHktYXBpLWNsaWVudCJdLCJuYmYiOjE3NzI0NzkzMzYsImV4cCI6MTc3MjQ4MjkzNn0.0hfuMeHofj0Ymf3Z1SZpMjDK1wpB2YLtigCISOj3Q8o

@userId2 = 019c7b93-e9f3-74f1-9bba-ea006eef944b
@username2 = testuser1
@email2 = test1@example.com
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTljYWU2NS0wZDMyLTcyYTYtYjYxYS1mMzk1Mjk2ZGJhNGMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWNhZTY1LTBkMzItNzJhNi1iNjFhLWYzOTUyOTZkYmE0YyIsImp0aSI6IjhiYjFlMTIxLWJmODMtNGEzOC04NzkxLWIzOWJiZjc3NDgyNSIsImlzcyI6ImJsb2ctY29tbXVuaXR5LWFwaSIsImF1ZCI6WyJibG9nLWNvbW11bml0eS1hcGktY2xpZW50IiwiYmxvZy1jb21tdW5pdHktYXBpLWNsaWVudCJdLCJuYmYiOjE3NzI0Nzk5ODQsImV4cCI6MTc3MjQ4MzU4NH0.5XtnXzHlfAjk4LSsqVN7j5LkvxWK04x6HcBTMtuYWs4

### Get By User ID
GET {{blog_community_api_HostAddress}}/users/{{userId1}}
##Authorization: Bearer {{token}}
Accept: application/json

### Get By Username
GET {{blog_community_api_HostAddress}}/users/{{username1}}
Accept: application/json

### Update User
PUT {{blog_community_api_HostAddress}}/users/{{userId1}}
Content-Type: application/json

{
  "username": "updatedUser",
  "email": "updated@example.com"
}

### Delete User
DELETE {{blog_community_api_HostAddress}}/users/{{userId1}}
Authorization: Bearer {{token1}}

### Create Category as testuser1
POST {{blog_community_api_HostAddress}}/categories
Authorization: Bearer {{token1}}
Content-Type: application/json

{
  "name": "Skiing"
}

### List Categories
GET {{blog_community_api_HostAddress}}/Categories

### Create Blog post as testuser1
POST {{blog_community_api_HostAddress}}/BlogPosts
Authorization: Bearer {{token1}}
Content-Type: application/json

{
  "categoryId": "3a6b0e59-4bf8-4fef-94b0-80c0b913f1b4",
  "title": "My First Post About Skiing",
  "content": "This is the content"
}

### List Blog posts
GET {{blog_community_api_HostAddress}}/blogposts

### Filter Blog posts by title
GET {{blog_community_api_HostAddress}}/blogposts?title=skiing

### Filter Blog posts by category
GET {{blog_community_api_HostAddress}}/BlogPosts?categoryId=3a6b0e59-4bf8-4fef-94b0-80c0b913f1b4

### Get Blog post by ID
GET {{blog_community_api_HostAddress}}/blogposts/a59b9d2e-438b-47f2-ab88-3e489d3e2ccc

### Update Blog post
PUT {{blog_community_api_HostAddress}}/blogposts/d6dcf7de-7b97-4950-8b9c-1c508cfe6e8c
Authorization: Bearer {{token1}}
Content-Type: application/json

{
  "categoryId": "cda2b101-f8bb-4859-9932-50a41e989ce2",
  "title": "My First Post About Fishing",
  "content": "Fishing stuff"
}

### Delete Blog post
DELETE {{blog_community_api_HostAddress}}/blogposts/98d4e0bc-1ef4-4342-87dd-a99c76b03a72 
Authorization: Bearer {{token1}}

### testuser2 comment on testuser1's post
POST {{blog_community_api_HostAddress}}/blogposts/d6dcf7de-7b97-4950-8b9c-1c508cfe6e8c/comments
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "content": "comment on skiing post"
}

### Get comments for post
GET {{blog_community_api_HostAddress}}/blogposts/d6dcf7de-7b97-4950-8b9c-1c508cfe6e8c/comments

### Comment own post test
POST {{blog_community_api_HostAddress}}/blogposts/d6dcf7de-7b97-4950-8b9c-1c508cfe6e8c/comments
Authorization: Bearer {{token1}}
Content-Type: application/json

{
  "content": "comment own post test"
}